### ISSUE TITLE
Support PHP 8.1, PHP 8.2 and PHP 8.3

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/sb-breadcrumbs-block#8]
Update code to run without problems in PHP 8.1, PHP 8.2, and PHP 8.3 with WordPress 6.4.1

See https://github.com/bobbingwide/bobbingwide/issues/103

**Comment by bobbingwide** [comment]
Update wp-scripts at the same time.

- After updating to v26.18.0 the build failed with `Error: Cannot find module 'react-refresh'`
- Reverting to v26.17.0, the version recently used for sb-chart-block, the build worked
- Trying again, having removed dependencies "@wordpress/create-block": "^4.31.0", it worked

**Comment by bobbingwide** [comment]
Delivered in v0.6.1
